credentials:

  token: 'Your API key'
  mail: 'Your mail address'

vinyls:

  # ---- TEMPLATE ----
  # add a new vinyl as follows:
  # vinyl_number: 
  #   cat: 'discogs release code'
  #   artist: 'optional info about artist'
  #   album: 'optional info about album'
  #   year: 1970
  #   info: 'optional info about the vinyl.'

  vinyl_1:
    cat: 'm10362'
    artist: 'Pink Floyd'
    album: 'The Dark Side Of The Moon'
    year: 1973
    info: 'Trippy Sounds ...'
  
  vinyl_2:
    cat: 'm10362'
    artist: 'Pink Floyd'
    album: 'The Dark Side Of The Moon'
    year: 1973
    info: 'Trippy Sounds ...'