credentials:

  token: ''
  mailReceiver: ''
  mailSender: ''
  senderPassword: ''

vinyls:

  # ---- TEMPLATE ----
  # add a new vinyl as follows:
  # vinyl_number: 
  #   cat: 'discogs release code'
  #   artist: 'optional info about artist'
  #   album: 'optional info about album'
  #   year: 1970
  #   info: 'optional info about the vinyl.'

  vinyl_1:
    cat: 'SHVL 804, 1E 064 o 05249'
    artist: 'Pink Floyd'
    album: 'The Dark Side Of The Moon'
    year: 1973
    info: 'Trippy Sounds ...'

  vinyl_2:
    cat: 'HCR-13'
    artist: 'Dropdead'
    album: 'Rapture'
    year: 1992
    info: 'random ...'